spring:
  application:
    name: ffc
  data:
    mongodb:
      database: ffc
      auto-index-creation: true
  mvc:
    format:
      date: iso

#logging:
#  level:
#    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
