spring:
  application:
    name: ffc
  data:
    mongodb:
      database: ffc
      auto-index-creation: true
  mvc:
    format:
      date: iso

adapters:
  omdb:
    url: "http://www.omdbapi.com"
    api-key: "change-me"

feign:
  client:
    config:
      default:
        loggerLevel: basic

server:
  error:
    include-message: always

logging:
  level:
    pl.tinylinden.ffc: trace
